[pytest]
testpaths = tests
pythonpath = src
markers =
    gui: marks tests that use Qt GUI elements (deselect with '-m "not gui"')
addopts = -v
;addopts = -rA -q -s -v -vv -o console_output_style=classic -p no:sugar --no-header --no-summary --tb=short
;addopts = -v --tb=short  --capture=fd --show-capture=no -p no:logging -o console_output_style=classic
minversion = 7.0