#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")

if [ -z "$FILES" ]; then
    exit 0
fi

if [ -f ".venv/Scripts/black.exe" ]; then
    FORMATTER=".venv/Scripts/black.exe"
elif [ -f ".venv/Scripts/black" ]; then
    FORMATTER=".venv/Scripts/black"
else
    echo "black not found, skipping formatting"
    exit 0
fi

$FORMATTER $FILES
git add $FILES